sudo: required
language: generic

#require docker
services:
  - docker

before_install:
  - docker build -t kheneahmares/travelogapi-test .

script:
  - docker run -e CI=true kheneahmares/travelogapi-test dotnet test