#build project for prod use
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as build

WORKDIR /app

COPY *.sln .
COPY ./TravelogApi/*.csproj ./TravelogApi/
COPY ./Domain/*.csproj ./Domain/
COPY ./DataAccess/*.csproj ./DataAccess/
COPY ./Persistence/*.csproj ./Persistence/
COPY ./Business/*.csproj ./Business/
COPY ./TravelogApi.Tests/*.csproj ./TravelogApi.Tests/

RUN dotnet restore

COPY ./TravelogApi/. ./TravelogApi/
COPY ./Domain/. ./Domain
COPY ./DataAccess/. ./DataAccess/
COPY ./Persistence/. ./Persistence/
COPY ./Business/. ./Business/
COPY ./TravelogApi.Tests/. ./TravelogApi.Tests/

CMD ["dotnet", "test"]
