#build project for prod use
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as build

WORKDIR /app

COPY *.sln .
COPY ./TravelogApi/*.csproj ./TravelogApi/
COPY ./Domain/*.csproj ./Domain/
COPY ./DataAccess/*.csproj ./DataAccess/
COPY ./Persistence/*.csproj ./Persistence/

RUN dotnet restore

COPY ./TravelogApi/. ./TravelogApi/
COPY ./Domain/. ./Domain
COPY ./DataAccess/. ./DataAccess/
COPY ./Persistence/. ./Persistence/

WORKDIR /app/TravelogApi
EXPOSE 5003

ENTRYPOINT [ "dotnet", "watch", "run", "--no-restore", "--urls", "https://host.docker.internal:5003" ]